[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn webapp:app --workers=1 --worker-class=gthread --threads=8 --timeout=0 --bind=0.0.0.0:$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
